### ISSUE TITLE
Update docs to show how to get access to the SignalR types in typescript if needed

### ISSUE THREAD

**Issue by gregveres** [cojamru/signalr-no-jquery#2]
I already have a fork of signal-no-jquery from DVLP's original version so GitHub is making it difficult to create a fork of your fork to provide a PR. So, here are the changes to the Readme.md file that I would suggest...

#### Usage with Typescript

Out of the box, this package exports hubConnection and includes @types/signalr as a dependency. If you need to access any signalr types other than just hubConnect, you can do it by accessing the SignalR namespace. For instance, if you need to capture the hubConnection results in a variable you can do it like this:

```js
import { hubConnection } from '@cojam/signalr-no-jquery';

const signalR: SignalR.Hub.Connection;
const hubProxy: SignalR.Hub.Proxy;
...
signalR = hubConnection();
hubProxy = signalR.createHubProxy('hubNameString');
```

**Comment by e965** [comment]
@gregveres no problem 👍

You can transfer your fork, for example, to any organization under your control (or create a new one). You can also try renaming the repository (but I don't know if that helps). Anyway, if you use my fork, you will no longer need yours, and you can just delete it.

Then try to create a pull request, and I will merge it to the project.

**Comment by kdcho** [comment]
@e965 First, thanks for this repo.
I tried implementing this lib but for the love of god, I can't figure out how to set the connection transport type to websocket. Could you possibly give me a hint? :)

**Comment by e965** [comment]
@kdcho in my company, we have recently migrated to the .NET Core version, so I won't tell you exactly, but it seems to be done something like this:

```js
import { hubConnection } from '@cojam/signalr-no-jquery';

const connectrion = hubConnection(/* your settings */);

...

connection.start({ transport: ['webSockets'] });
```

docs: https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr#specifying-a-transport

**Comment by kdcho** [comment]
Thank you @e965. Maybe I'm doing something totally wrong here but with websockets I should be able to skip negotiation, right? 
This is my code and I get a CORS error because when the connection is build it fails. First I tried the SignalR lib for CORE which obviously didn't work as I'm working with a ASP.NET Framework currently but there I could just add "skipNegotiation: true" and if would try to connect. Unfortunately, with this lib there are no negotiation options for, in this case, hubConnection. Or maybe there is and I don't see it. Could you give me a hand here?

```javascript
export class SignalRService {
        config: ConfigModel
        connection: any
        signalR: SignalR.Hub.Connection
        hubProxy: SignalR.Hub.Proxy

        private messages$ = new BehaviorSubject<ExportMessage>(new ExportMessage())
        messages = this.messages$.asObservable()

        constructor(private httpService: HttpService) {
            this.config = this.httpService.config
            this.buildHubConnection()
        }

        private buildHubConnection(): void {
            /* const hubConnectionUrl = `${this.config['api']}` */
            const hubConnectionUrl = 'http://localhost:57037/'

            this.connection = hubConnection(hubConnectionUrl, { logging: true })
            this.hubProxy = this.connection.createHubProxy('RetailerHub')

            this.registerOnServerEvents()
        }

        startConnection(labsite: string): any {
            from(this.connection.start())
                .pipe(
                    map((_) => {
                        this.connection.invoke('JoinLabsite', labsite)
                    }),
                    retry(3)
                )
                .subscribe()
        }

        private registerOnServerEvents(): void {
            this.hubProxy.on('ExportStatusChanged', (data: ExportMessage) => {
                this.messages$.next(data)
            })
            this.hubProxy.on('ExportWarning', (data: ExportMessage) => {
                this.messages$.next(data)
            })
        }
    }

**Comment by gregveres** [comment]
I am using this with an ASP.Net MVC app on the back end. I don't set any options and it negotiates properly to use websockets when it can.  On the .Net side, I am using these Nuget packages:
Microsoft.AspNet.SignalR: v2.4.1
Microsoft.AspNet.SignalR.Core: v2.4.1
Microsoft.AspNet.SignalR.SystemWeb: v2.4.1

This is the request flow that I see in the chrome debugger network tab:
A normal XHR request:
http://localhost:50447/signalr/negotiate?clientProtocol=2.0&connectionData=%5B%7B%22name%22%3A%22matchresulthub%22%7D%2C%7B%22name%22%3A%22chathub%22%7D%5D&_=1618239351034

then a websocket request:
ws://localhost:50447/signalr/connect?transport=webSockets&clientProtocol=2.0&connectionToken=tFB8pQ8JsNTG4mOngw9kJ3dnFOgI%2BNTWGWJISEnuoKjXGQkqB0ZOtPWhVZ%2BrRVRfHHgD%2FAPhKOnJQjib0yuOZvhi0fhqEFLtVK4QbQqMo2gzQtb73eZNEH%2BLdfxEvs6FcWWava480MhQRuMLlnbjVw%3D%3D&connectionData=%5B%7B%22name%22%3A%22matchresulthub%22%7D%2C%7B%22name%22%3A%22chathub%22%7D%5D&tid=0

Then an XHR request to start the connection:
http://localhost:50447/signalr/start?transport=webSockets&clientProtocol=2.0&connectionToken=tFB8pQ8JsNTG4mOngw9kJ3dnFOgI%2BNTWGWJISEnuoKjXGQkqB0ZOtPWhVZ%2BrRVRfHHgD%2FAPhKOnJQjib0yuOZvhi0fhqEFLtVK4QbQqMo2gzQtb73eZNEH%2BLdfxEvs6FcWWava480MhQRuMLlnbjVw%3D%3D&connectionData=%5B%7B%22name%22%3A%22matchresulthub%22%7D%2C%7B%22name%22%3A%22chathub%22%7D%5D&_=1618239351038

Then a websocket connrect request:
ws://localhost:50447/signalr/connect?transport=webSockets&clientProtocol=2.0&connectionToken=y%2BJlVy5kjLx1xUUZJJ8RpmzV7tUE%2BRlbD%2BPwigOY4ERNmLqu9Ms0Vnh0RrjSQ%2BHv9FqQ9vagK2BIzbyiOlPZ%2FLb6xxK%2FZP58tEagrlOXcoQGUbVB7O2SfaCBgvRFO2xMrI5otNdlM0IA8moBqXzzPg%3D%3D&connectionData=%5B%7B%22name%22%3A%22matchresulthub%22%7D%2C%7B%22name%22%3A%22chathub%22%7D%5D&tid=3

Hope this helps.

**Comment by e965** [comment]
Closed due to inactivity.
