### ISSUE TITLE
could you pull in SignalR 2.4.2?

### ISSUE THREAD

**Issue by gregveres** [cojamru/signalr-no-jquery#3]
It has been updated to fix a bug introduced with recent versions of Chrome.
Here is the signalR issue: [SignalR/SignalR#4536
](https://github.com/SignalR/SignalR/issues/4536)

**Comment by gregveres** [comment]
@e965 Hi Dmitry would you be able to pull in the latest version and do a new npm update?
That would be much appreciated!

**Comment by e965** [comment]
@gregveres Sorry, I was busy with work all month. I took the time and made the release of version [0.3.0](https://github.com/cojamru/signalr-no-jquery/releases/tag/0.3.0) with a bunch of changes.

Please check that everything is fine. I currently have no way to check if the library is working correctly.

**Comment by gregveres** [comment]
Thank you. It is working fine.
