### ISSUE TITLE
Is the long-polling transport type supported?

### ISSUE THREAD

**Issue by TimWillebrands** [cojamru/signalr-no-jquery#4]
We've had some issues with customers unable to receive messages when they're connecting with longpolling and if I force the client locally to connect with longpolling it fails as well. Is there an issue with longpolling using this no-jquery solution?

Repro: Connect like this:
`await connection.start({transport:'longPolling'});`
And request the server to send some messages to the connected client.

**Comment by e965** [comment]
When I tested the package (this was a long time ago), all supported transport types worked. You may be having problems server settings.

Closed due to inactivity.
